name: Quarto Publish
on:
  push:
    branches: main
    paths:
      - '**.qmd'
      - '**.Rmd'
      - '**.md'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.R_GITHUB_PAT }}
      R_REPOS_URL: "https://cloud.r-project.org"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'  # Specify exact version for stability
          
      - name: Set up R package management
        run: |
          echo '.libPaths(c("/home/runner/work/r-packages", .libPaths()))' >> ~/.Rprofile
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ~/.Rprofile
          mkdir -p /home/runner/work/r-packages

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: /home/runner/work/r-packages
          key: r-${{ runner.os }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: r-${{ runner.os }}-

      - name: Install required R packages
        run: |
          install.packages(c("renv", "remotes"))
          renv::restore()
        shell: Rscript {0}

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true