name: Quarto Publish

on:
  push:
    branches: main
    paths:
      - '**.qmd'
      - '**.Rmd'
      - '**.md'
      - '_quarto.yml'
    paths-ignore:
      - 'mafft/**'
      - 'u2data/**'
      - 'u2gigs/**' 
      - 'u2hvl/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.R_GITHUB_PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.posit.co/cran/__linux__/jammy/latest
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libfreetype6-dev libfribidi-dev \
            libharfbuzz-dev libjpeg-dev libpng-dev libtiff-dev \
            libproj-dev libgdal-dev libgeos-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          repository: vanleeuwen-hans/u2_data_analytics_data
          token: ${{ secrets.U2_DATA_ANALYTICS_DATA_TOKEN }}
          path: u2_data_analytics_data
    
      - name: Cache Quarto build
        uses: actions/cache@v3
        with:
          path: ~/.cache/quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('**/renv.lock', '_quarto.yml') }}
          restore-keys: |
            ${{ runner.os }}-quarto-

      - name: Setup renv and restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::init(bare = TRUE)
          renv::restore()

      - name: Copy data/image files from private repository
        run: |
          cp -r u2_data_analytics_data/mafft .
          cp -r u2_data_analytics_data/u2data .
          cp -r u2_data_analytics_data/u2gigs .
          cp -r u2_data_analytics_data/u2hvl .

      - name: Render full Quarto project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Create .nojekyll
        run: touch docs/.nojekyll

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs